name: ready_food
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
# Dependencias de Firebase
  firebase_core: ^1.12.0
  firebase_auth: ^3.3.7
  firebase_database: ^9.0.6
  firebase_storage: ^10.2.9
#  Dependencia de notificaciones dentro de la app
  advance_notification: ^1.0.5
# Dependencia para validar la conectividad 
  connectivity: ^3.0.6
# Dependencia para escanear códigos QR
  qrscan: ^0.3.2
# Dependencia para gestionar permisos
  permission_handler: ^9.1.0
# Dependencia de estilo IOS
  cupertino_icons: ^1.0.2
# Dependencia para guardar imagenes
  image_gallery_saver: ^1.7.1
# Dependencia para animar un widget
  animate_do: ^2.1.0
# Dependencia para los customs modals
  modal_bottom_sheet: ^2.0.0
# Dependencia para génerar ID 
  uuid: ^3.0.6
# Dependencia para la selección de imagenes
  image_picker: ^0.8.4+10
# Dependencia para visualizar imagenes en pantalla completa
  easy_image_viewer: ^1.0.3
# Gestor de estados
  provider: ^6.0.2
# Dependecncia para el refresh
  flutter_easyrefresh: ^2.2.1
# Dependencia para el drawer
  flutter_hidden_drawer: ^1.0.1
# Dependencia para lanzar otras apps
  url_launcher: ^6.0.20
# Dependencia para los botones de acción
  simple_speed_dial: ^0.1.3
# Dependencia para las notificaciones PUSH
  firebase_messaging: ^11.2.11
# Dependencia para hacer peticiones http
  http: ^0.13.4
# Dependencia para los toas
  motion_toast: ^2.1.3
# Dependencia para las gráficas
  chart_components: ^1.0.1
# Dependencia para indicador de porcentajes
  percent_indicator: ^4.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - lib/img/
    - lib/models/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
